language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
before_install: gem install bundler -v 1.10.5
gemfile:
  - Gemfile
services: redis
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2